type t = {mutable head: int}
@new @module("@popstarfreas/packetfactory/bufferreader.js")
external make: NodeJs.Buffer.t => t = "default"
@send external readByte: t => int = "readByte"
@send external readBytes: (t, int) => array<int> = "readBytes"
@send external readBuffer: (t, int) => NodeJs.Buffer.t = "readBuffer"
@send external readColor: t => Color.t = "readColor"
@send external readSByte: t => int = "readSByte"
@send external readInt16: t => int = "readInt16"
@send external readUInt16: t => int = "readUInt16"
@send external readInt32: t => int = "readInt32"
@send external readUInt32: t => int = "readUInt32"
@send external readInt64: t => NodeJs.BigInt.t = "readInt64"
@send external readUInt64: t => NodeJs.BigInt.t = "readUInt64"
@send external readSingle: t => float = "readSingle"
@send external readString: t => string = "readString"
@send external readNetworkText: t => NetworkText.t = "readNetworkText"
@get external getBytesLeft: t => int = "bytesLeft"
